### ISSUE TITLE
没事了

### ISSUE THREAD

**Issue by Wlazly** [shiwei-Ren/smpe-admin-web#13]
ddd

**Comment by shiwei-Ren** [comment]
什么项目？



---原始邮件---
发件人: "Wlazly"<notifications@github.com&gt;
发送时间: 2020年12月16日(周三) 晚上7:14
收件人: "shiwei-Ren/smpe-admin-web"<smpe-admin-web@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [shiwei-Ren/smpe-admin-web] 你好，你之前fork了我们公司的两个项目，请及时删除 (#13)




 
你们fork了我们公司员工自己上传的两个项目，现公司要求紧急删除项目，请配合，谢谢了。具体联系微信wazhqiang

**Comment by Wlazly** [comment]
MKN0_Android和Movetime，请帮忙删除下，谢谢了。

**Comment by shiwei-Ren** [comment]
我不记得我fork这两个项目啊，我又不是学anroid，你是不是搞错了



---原始邮件---
发件人: "Wlazly"<notifications@github.com&gt;
发送时间: 2020年12月16日(周三) 晚上9:24
收件人: "shiwei-Ren/smpe-admin-web"<smpe-admin-web@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"shiwei-Ren"<1487660836@qq.com&gt;;
主题: Re: [shiwei-Ren/smpe-admin-web] 你好，你之前fork了我们公司的两个项目，请及时删除 (#13)




 
MKN0_Android和Movetime，请帮忙删除下，谢谢了。

**Comment by Wlazly** [comment]
不好意思，搞错人了，抱歉

**Comment by shiwei-Ren** [comment]
没事没事



---原始邮件---
发件人: "Wlazly"<notifications@github.com&gt;
发送时间: 2020年12月16日(周三) 晚上10:01
收件人: "shiwei-Ren/smpe-admin-web"<smpe-admin-web@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"shiwei-Ren"<1487660836@qq.com&gt;;
主题: Re: [shiwei-Ren/smpe-admin-web] 你好，你之前fork了我们公司的两个项目，请及时删除 (#13)




 
不好意思，搞错人了，抱歉
